[package]
name = "chip8-gui"
version = "0.1.0"
edition = "2021"

[dependencies]
pixels = "0.13.0"
game-loop = { version = "0.10.2", features = ["winit"] }
chip8 = { version = "0.1.0", path = "../chip8" }
